name: rl_reward_sol
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - scipy
  - jupyter
  - pip:
      - gymnasium[box2d]
      - stable-baselines3[extra]
